### ISSUE TITLE
[Bug] Errors on installing go-prompt via go get in Ubuntu 18

### ISSUE THREAD

**Issue by oborshchak** [c-bata/go-prompt#190]
# Bug reports

Got the errors in the system terminal on installing the **go-prompt** package via command
`go get github.com/c-bata/go-prompt` in Ubuntu 18.

## Expected Behavior

Package has been downloaded and installed, can be used for program build (i.e. via go run, go build).

## Current Behavior and Steps to Reproduce

On installing via the command `go get github.com/c-bata/go-prompt` in Ubuntu 18 (and in docker with images golang:1.13 or golang:1.14)  got the errors

`
../../c-bata/go-prompt/internal/term/raw.go:27:75: cannot use (*syscall.Termios)(&n) (type *syscall.Termios) as type *unix.Termios in argument to termios.Tcsetattr
`
`
../../c-bata/go-prompt/internal/term/term.go:22:40: cannot use &saveTermios (type *syscall.Termios) as type *unix.Termios in argument to termios.Tcgetattr
`
`
../../c-bata/go-prompt/internal/term/term.go:33:68: cannot use &o (type *syscall.Termios) as type *unix.Termios in argument to termios.Tcsetattr
`

Tried to use go modules, and install a particular release (tag), alike 
`go get -v github.com/c-bata/go-prompt@v0.2.0` but none of them helps (tried all 6 releases) -  no changes, the same errors.

At the same time, in the Windows WSL with Ubuntu 18 the package is being installed w/o errors and can be used as expected.

## Context

* Operating System: Ubuntu 18 (Linux 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux); docker images golang:1.13 or golang:1.14
* Go version: on Ubuntu 18 - where errors occur: 1.14.1; on Windows WSL / Ubuntu 18: 1.14
* Terminal Emulator: none (fails on installing step)
* tag: any release

Thanks for your help!

**Comment by pgollangi** [comment]
I have also encountered with same error while `go build` on Ubuntu. It was failing my CI/CD since it cannot build. This error was initially detected by `go vet`

**Comment by VijayanB** [comment]
It fails on mac as well

**Comment by pgollangi** [comment]
To start with, this issue was introduced with https://github.com/pkg/term/pull/51 to fix https://github.com/pkg/term/issues/49  where arguments of function `termios.Tcsetattr` has been changed from `system.Termios` to `unix.Termios`. This was the primary reason for this error.

However `go-prompt` uses version `v0.0.0-20180423043932-cda20d4ac917` of `github.com/pkg/term` which is compatible with it. `go-prompt` works well as long as you use this particular version of `term`.

To me, I have encounter with this problem as my module has explicit used dependency of latest version `github.com/pkg/term` `v1.0.0`.  Hence the incompatible arguments errors occurred. It was added by `go tidy` for me.
@oborshchak you must be having similar problem. 

So as a workaround you can explicit use `v0.0.0-20180423043932-cda20d4ac917` of `github.com/pkg/term` by updating your go module to fix this problem.

I'm working on raising a PR to update fix this problem at `go-prompt`.

**Comment by c-bata** [comment]
@pgollangi Thank you for your investigation. Great job 👍 
I'll review your PR as soon as possible.

**Comment by pgollangi** [comment]
@c-bata thank you. I have raised #191 to address this problem.
