### ISSUE TITLE
dynamic / live prompt/prefix string.

### ISSUE THREAD

**Issue by jesseward** [c-bata/go-prompt#22]
hey @c-bata , awesome package..

I have logged a pull request and opening this issue to discuss a potential feature enhancement or suggestions for this change. 

PR https://github.com/c-bata/go-prompt/pull/21 introduces a new option 'prompt.OptionLivePrefix' that accepts a function (signature = func() string). This function would be called each time Render() is executed.

The goal here is to enable a "live" (or dynamic) prompt, as an alternative to the current static Prefix/prompt.

**Comment by warpfork** [comment]
Hi there @c-bata, +1 to awesome work and also +1 for interest in an ability to set additional prefix material.

I wrote something very simple for this [once before](https://github.com/polydawn/go-slog).  The user experience that library had in mind is roughly:

```
scrollback 1          each of these
scrollback 2          is a regular log line
scrollback 3          scrolling back forever (until your terminal gui runs out of scrollback anyway)
scrollback 4          and it's exposed as another io.Writer of course
scrollback ...n       
┌─────────────────────────────────────────────────────┐
│  you could make a "banner" here                     │
│  providing` some sort of service status, clock, etc  │
│  the height is also variable; why not               │
└─────────────────────────────────────────────────────┘
>>> user prompt would stick at the very bottom
```

I'd love to add something like this "Banner" feature to go-prompt.  The hacks I scraped together in the past do the banner part (implementation is simply setting the cursor back to the top of the banner area after every update and some ANSI clear codes -- very similar to what go-prompt does) work fine, but I never added user input, and go-prompts features for input are out of this world and I want to use it :D

Do you have any opinions on the API?  `go-slog`'s  API was just a simple `SetBanner` method (with a mutex internally).  I also tried a callback approach in an earlier draft, but scrapped it, because the `SetBanner` was much easier to integrate with other actors in my programs.  And a simple string argument (so internally the library counted the linebreaks as necessary to keep repaints consistent) was really all I ever needed.

Would be quite happy to make PRs if there's a design in mind!

**Comment by mozillazg** [comment]
+1 for dynamic prefix.

**Comment by c-bata** [comment]
Hi guys. I reopened #21 and add some comments for supporting live prefix.

**Comment by c-bata** [comment]
added at https://github.com/c-bata/go-prompt/pull/30
