### ISSUE TITLE
non interactive execution

### ISSUE THREAD

**Issue by keith6014** [c-bata/go-prompt#87]
Does go-prompt have a feature for non interactive execution?
Similar to https://github.com/abiosoft/ishell#non-interactive-execution ?

**Comment by keith6014** [comment]
@c-bata will non interactive execution work?

**Comment by keith6014** [comment]
I am very curious about this otherwise if anyone knows of another library please let me know.

**Comment by egorse** [comment]
You mean parse args, make string from slice and pass it to executor? Is that really complex?

**Comment by c-bata** [comment]
@keith6014 Now I think go-prompt should focus one thing just provide interactive prompts because small is beautiful. I think the interface and the implementation will be complex if this feature is added. This is why I don't wanna implement this.

But I know there are such needs @keith6014 said. I think one solution is to convert definition of command line interface to `Completer` of go-prompt. For example, `kubectl` is implemented using  [spf13/cobra](https://github.com/spf13/cobra) and we may be able to automatically generating `prompt.Completer` from `cobra.Command` like:

https://github.com/c-bata/kube-prompt/issues/18

Actually @stormland has already implemented [stormland/cobra-prompt](https://github.com/stromland/cobra-prompt). It seems cobra-prompt doesn't properly work but if we can do this, go-prompt will be more convenient software.

**Comment by egorse** [comment]
@c-bata What about next example - works with ```app -c uptime```

```
package main

import (
	"flag"
	"os"
	"os/exec"
	"strings"

	"github.com/c-bata/go-prompt"
)

func executor(t string) {
	if t == "bash" || t == "uptime" {
		cmd := exec.Command(t)
		cmd.Stdin = os.Stdin
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		cmd.Run()
	} else if t == "exit" {
		os.Exit(0)
	}

	return
}

func completer(in prompt.Document) []prompt.Suggest {
	s := []prompt.Suggest{
		{Text: "bash", Description: "Run bash"},
		{Text: "uptime", Description: "Show uptime"},
		{Text: "exit", Description: "Exit shell"},
	}
	return prompt.FilterHasPrefix(s, in.GetWordBeforeCursor(), true)
}

func main() {
	var c bool
	flag.BoolVar(&c, "c", false, "execute command")
	flag.Parse()
	rest := flag.Args()

	// Non-interactive execution
	if c {
		cmd := strings.Join(rest, " ")
		executor(cmd)
		os.Exit(0)
		return
	}

        // Interactive execution
	p := prompt.New(
		executor,
		completer,
	)
	p.Run()
}
```

**Comment by c-bata** [comment]
@egorse Seems good 👍 Command line arguments might be room for improvements. Basically the usage of non-interactive execution should be the same with prompt mode. In your example, we need to type `-c`. `supervisorctl` which is the CLI for supervisord(daemons manager in python) is good example. If execute `$ supervisorctl status`, supervisorctl prints the status and exits. On the other hand, If execute `$ supervisorctl` without subcommand, interactive shell will start.
http://supervisord.org/running.html#running-supervisorctl

**Comment by egorse** [comment]
@c-bata my point was - non-interactive call is just call to executor.

probably something as  ```prompt.Exec(cmd string)``` could be good as for documenting as well some terminal handling around call to executor.

**Comment by keith6014** [comment]
Thanks for the responses and code samples!
I though you abandoned the project! :-)

@c-bata : i was thinking something similar to your supervisorctl example. So, if I did supervisorctl "status" then it would run the status.

@egorse.
Thanks for the code example. I would be ok with using -c.
Do you have an example with prompt.Exec?

**Comment by egorse** [comment]
@keith6014  there is no prompt.Exec() - that was just seed for @c-bata opinion. If there would be such method - then main would looks like (also made it acting as ```supervisorctl status```):
```
func main() {
	p := prompt.New(
		executor,
		completer,
	)

	args := flag.Args()
	if len(args) != 0 { // Non-interactive execution
		cmd := strings.Join(args, " ")
		prompt.Exec(cmd)
		return
	}

        // Interactive execution
	p.Run()
}
```
